# Generated by Django 3.0.5 on 2020-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(),
        ),
    ]
